source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

inhibit_all_warnings!
use_frameworks!

workspace 'UserProfile'

target 'UserProfile' do
  pod 'SwiftGen', '6.5.1'  
  pod 'UserProfileInterface', :path => '../UserProfileInterface'
  pod 'Components', :path => '../../Components'

  target 'UserProfileTests' do
      #pod 'Dependency', '~> 1.0.0'
  end
end

target 'SampleApp' do
  project 'SampleApp/SampleApp'
  pod 'UserProfile', :path => './'
  pod 'UserProfileAssembly', :path => '../UserProfileAssembly'

  # DI
  pod 'Swinject', '~> 2.0'
  pod 'SwinjectAutoregistration', '~> 2.0'

end
