
source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

inhibit_all_warnings!
use_frameworks!

workspace 'Confirmation'

target 'Confirmation' do

  pod 'SwiftLint'
  
  target 'ConfirmationTests' do
  end
end

target 'SampleApp' do
  project 'SampleApp/SampleApp'
  pod 'Confirmation', :path => './'
end