source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

inhibit_all_warnings!
use_frameworks!

workspace 'ContactList'

target 'ContactList' do
  pod 'SwiftGen', '6.5.1'  
  pod 'ContactListInterface', :path => '../ContactListInterface'
  pod 'Components', :path => '../../Libraries/Components'

  target 'ContactListTests' do
      #pod 'Dependency', '~> 1.0.0'
  end
end

target 'SampleApp' do
  project 'SampleApp/SampleApp'
  pod 'ContactList', :path => './'
  pod 'ContactListAssembly', :path => '../ContactListAssembly'

  # DI
  pod 'Swinject', '~> 2.0'
  pod 'SwinjectAutoregistration', '~> 2.0'

end