source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

inhibit_all_warnings!
use_frameworks!

workspace 'UserProfile'

target 'UserProfile' do
  pod 'SwiftGen', '6.5.1'  
  pod 'UserProfileInterface', :path => '../UserProfileInterface'
  pod 'Components', :path => '../Components'
  pod 'FinanceFoundations', :path => '../FinanceFoundations'
  target 'UserProfileTests' do
      #pod 'Dependency', '~> 1.0.0'
  end
end

target 'SampleApp' do
  project 'SampleApp/SampleApp'
  pod 'UserProfile', :path => './'
  pod 'UserProfileAssembly', :path => '../UserProfileAssembly'
  
  # DI
  pod 'Swinject', '~> 2.0'
  pod 'SwinjectAutoregistration', '~> 2.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
