
source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

inhibit_all_warnings!
use_frameworks!

workspace 'ActivityDetails'

target 'ActivityDetails' do

  pod 'SwiftLint'
  pod 'SwiftGen', '6.5.1'

  target 'ActivityDetailsTests' do
  end
end

target 'SampleApp' do
  project 'SampleApp/SampleApp'
  pod 'ActivityDetails', :path => './'
end