source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

inhibit_all_warnings!
use_frameworks!

workspace 'ContactList'

target 'ContactList' do
  pod 'SwiftGen', '6.5.1'  
  pod 'ContactListInterface', :path => '../ContactListInterface'
  pod 'FinanceFoundations', :path => '../FinanceFoundations'
  
  target 'ContactListTests' do
      #pod 'Dependency', '~> 1.0.0'
  end
end

target 'SampleApp' do
  project 'SampleApp/SampleApp'
  pod 'ContactList', :path => './'
  pod 'ContactListAssembly', :path => '../ContactListAssembly'
  pod 'Components', :path => '../Components'
  
  
  # DI
  pod 'Swinject', '~> 2.0'
  pod 'SwinjectAutoregistration', '~> 2.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
