# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

# plugin 'cocoapods-dependency-graph'
# dependency_output :graph

def libraries
  # pod 'FinanceService', :path => 'Libraries/FinanceService'
  # pod 'FinanceFoundations', :path => 'Libraries/FinanceFoundations'
  pod 'Transfers', :path => 'Libraries/Transfers'
  pod 'Components', :path => 'Libraries/Components'
  pod 'UserProfile', :path => 'Libraries/UserProfile'
  
  pod 'ActivityDetails', :path => 'Libraries/ActivityDetails'
  pod 'Confirmation', :path => 'Libraries/Confirmation'
  pod 'Home', :path => 'Libraries/Home'
  pod 'ContactList', :path => 'Libraries/ContactList'
end

def uifeatures
  # old SDK's
  # pod 'FinanceService', :path => 'Libraries/FinanceService'
  # pod 'FinanceFoundations', :path => 'Libraries/FinanceFoundations'
  pod 'Components', :path => 'Libraries/Components'
  
  # new sdk's
  pod 'ActivityDetails', :path => 'UIFeatures/ActivityDetails'
  pod 'ActivityDetailsAssembly', :path => 'UIFeatures/ActivityDetailsAssembly'
  pod 'ActivityDetailsInterface', :path => 'UIFeatures/ActivityDetailsInterface'
  
  pod 'Home', :path => 'UIFeatures/Home'
  pod 'HomeAssembly', :path => 'UIFeatures/HomeAssembly'
  pod 'HomeInterface', :path => 'UIFeatures/HomeInterface'
  
  pod 'UserProfile', :path => 'UIFeatures/UserProfile'
  pod 'UserProfileAssembly', :path => 'UIFeatures/UserProfileAssembly'
  pod 'UserProfileInterface', :path => 'UIFeatures/UserProfileInterface'

  pod 'Confirmation', :path => 'UIFeatures/Confirmation'
  pod 'ConfirmationAssembly', :path => 'UIFeatures/ConfirmationAssembly'
  pod 'ConfirmationInterface', :path => 'UIFeatures/ConfirmationInterface'
  
  pod 'ContactList', :path => 'UIFeatures/ContactList'
  pod 'ContactListAssembly', :path => 'UIFeatures/ContactListAssembly'
  pod 'ContactListInterface', :path => 'UIFeatures/ContactListInterface'
  
  pod 'Transfers', :path => 'UIFeatures/Transfers'
  pod 'TransfersAssembly', :path => 'UIFeatures/TransfersAssembly'
  pod 'TransfersInterface', :path => 'UIFeatures/TransfersInterface'
  
end

target 'FinanceApp' do
  
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'SwiftLint'
  libraries

  target 'FinanceAppTests' do
    # Pods for testing
  end

  target 'FinanceAppUITests' do
    # Pods for testing
  end

end
