# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

target 'FinanceApp' do
  
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'SwiftLint'
  pod 'FinanceService', :path => 'Libraries/FinanceService'
  pod 'Transfers', :path => 'Libraries/Transfers'
  pod 'Components', :path => 'Libraries/Components'
  pod 'UserProfile', :path => 'Libraries/UserProfile'
  pod 'FinanceFoundations', :path => 'Libraries/FinanceFoundations'
  pod 'ActivityDetails', :path => 'Libraries/ActivityDetails'
  pod 'Confirmation', :path => 'Libraries/Confirmation'

  target 'FinanceAppTests' do
    # Pods for testing
  end

  target 'FinanceAppUITests' do
    # Pods for testing
  end

end
