
source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

inhibit_all_warnings!
use_frameworks!

workspace 'Home'

target 'Home' do

  pod 'SwiftLint'
  pod 'SwiftGen', '6.5.1'
  pod 'Components', :path => '../Components'

  target 'HomeTests' do
      #pod 'Dependency', '~> 1.0.0'
  end
end

target 'SampleApp' do
  project 'SampleApp/SampleApp'
  pod 'Components', :path => '../Components'
  pod 'Home', :path => './'
end