
source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

inhibit_all_warnings!
use_frameworks!

workspace 'ContactList'

target 'ContactList' do
  pod 'SwiftLint'
  pod 'SwiftGen'

  target 'ContactListTests' do
  end
end

target 'SampleApp' do
  project 'SampleApp/SampleApp'
  pod 'ContactList', :path => './'
end