source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

inhibit_all_warnings!
use_frameworks!

workspace 'Confirmation'

target 'Confirmation' do
  pod 'SwiftGen', '6.5.1'  
  pod 'ConfirmationInterface', :path => '../ConfirmationInterface'

  target 'ConfirmationTests' do
      #pod 'Dependency', '~> 1.0.0'
  end
end

target 'SampleApp' do
  project 'SampleApp/SampleApp'
  pod 'Confirmation', :path => './'
  pod 'ConfirmationAssembly', :path => '../ConfirmationAssembly'

  # DI
  pod 'Swinject', '~> 2.0'
  pod 'SwinjectAutoregistration', '~> 2.0'

end