# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

target 'FinanceApp' do
  
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'SwiftLint'
  pod 'ActivityDetails', :path => 'Libraries/ActivityDetails'
  pod 'Components', :path => 'Libraries/Components'
  pod 'Confirmation', :path => 'Libraries/Confirmation'
  pod 'ContactList', :path => 'Libraries/ContactList'
  pod 'FinanceExtensions', :path => 'Libraries/FinanceExtensions'
  pod 'FinanceService', :path => 'Libraries/FinanceService'
  pod 'Home', :path => 'Libraries/Home'
  pod 'Transfers', :path => 'Libraries/Transfers'
  pod 'UserProfile', :path => 'Libraries/UserProfile'
  
  target 'FinanceAppTests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
