# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

target 'FinanceApp' do
  
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'SwiftLint'
  pod 'FinanceService', :path => 'Libraries/FinanceService'
  
  target 'FinanceAppTests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
