
source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

inhibit_all_warnings!
use_frameworks!

workspace 'FinanceExtensions'

target 'FinanceExtensions' do

  pod 'SwiftLint'
  pod 'SwiftGen', '6.5.1'

  target 'FinanceExtensionsTests' do
      # pod 'Dependency', '~> 1.0.0'
  end
end

target 'SampleApp' do
  project 'SampleApp/SampleApp'
  pod 'FinanceExtensions', :path => './'
end