source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

inhibit_all_warnings!
use_frameworks!

workspace 'ActivityDetails'

target 'ActivityDetails' do
  pod 'SwiftGen', '6.5.1'  
  pod 'ActivityDetailsInterface', :path => '../ActivityDetailsInterface'
  pod 'FinanceService', :path => '../../FinanceService'

  target 'ActivityDetailsTests' do
      #pod 'Dependency', '~> 1.0.0'
  end
end

target 'SampleApp' do
  project 'SampleApp/SampleApp'
  pod 'ActivityDetails', :path => './'
  pod 'ActivityDetailsAssembly', :path => '../ActivityDetailsAssembly'

  # DI
  pod 'Swinject', '~> 2.0'
  pod 'SwinjectAutoregistration', '~> 2.0'

end