source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

inhibit_all_warnings!
use_frameworks!

workspace 'Transfers'

target 'Transfers' do
  pod 'SwiftGen', '6.5.1'  
  pod 'TransfersInterface', :path => '../TransfersInterface'
  pod 'ConfirmationInterface', :path => '../ConfirmationInterface'
  pod 'ContactListInterface', :path => '../ContactListInterface'
  pod 'Components', :path => '../../Libraries/Components'

  target 'TransfersTests' do
      #pod 'Dependency', '~> 1.0.0'
  end
end

target 'SampleApp' do
  project 'SampleApp/SampleApp'
  pod 'Transfers', :path => './'
  pod 'TransfersAssembly', :path => '../TransfersAssembly'

  # DI
  pod 'Swinject', '~> 2.0'
  pod 'SwinjectAutoregistration', '~> 2.0'

end