# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

target 'FinanceApp' do
  
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'SwiftLint'
  pod 'FinanceService', :path => 'libraries/FinanceService'
  pod 'Confirmation', :path => 'libraries/Confirmation'
  pod 'ContactList', :path => 'libraries/ContactList'

  pod 'Components', :path => 'libraries/Components'
  pod 'UserProfile', :path => 'libraries/UserProfile'
  pod 'ActivityDetails', :path => 'libraries/ActivityDetails'
  pod 'Home', :path => 'libraries/Home'
  pod 'Transfers', :path => 'libraries/Transfers'


  target 'FinanceAppTests' do
    # Pods for testing
  end

end
