# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

target 'FinanceApp' do
  
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'SwiftLint'
  
  # UserProfile
  pod 'UserProfile', :path => 'libraries/FinanceUI/UserProfile'
  pod 'UserProfileInterface', :path => 'libraries/FinanceUI/UserProfileInterface'
  pod 'UserProfileAssembly', :path => 'libraries/FinanceUI/UserProfileAssembly'

  # Home
  pod 'Home', :path => 'libraries/FinanceUI/Home'
  pod 'HomeInterface', :path => 'libraries/FinanceUI/HomeInterface'
  pod 'HomeAssembly', :path => 'libraries/FinanceUI/HomeAssembly'

  # ContactList

  pod 'ContactList', :path => 'libraries/ContactList/ContactList'
  pod 'ContactListInterface', :path => 'libraries/ContactList/ContactListInterface'
  pod 'ContactListAssembly', :path => 'libraries/ContactList/ContactListAssembly'

  pod 'FinanceService', :path => 'libraries/FinanceService'
  pod 'Confirmation', :path => 'libraries/Confirmation'
  # pod 'ContactList', :path => 'libraries/ContactList'
  pod 'Components', :path => 'libraries/Components'
  pod 'ActivityDetails', :path => 'libraries/ActivityDetails'
  
  pod 'Transfers', :path => 'libraries/Transfers'

  target 'FinanceAppTests' do
    # Pods for testing
  end

end
