require 'rake'

# New Domain SDK
desc 'Create new SDK'
task :create_domain_sdk do
    ARGV.each { |name| task name.to_sym do ; end }

    name = ARGV[1]
    sh "cd Support/Scripts && ./create-sdk #{name}"
    sh "cd Support/Scripts && ./setup #{name}"
    sh "cd Support/Output/#{name}/ && open #{name}.xcworkspace"
end

desc 'Setup Project'
task :setup do
    
    ARGV.each { |name| task name.to_sym do ; end }
    name = ARGV[1]

    if name == "FinanceApp" 
        sh "xcodegen generate && pod install && open FinanceApp.xcworkspace"
    else 
        sh "cd libraries/#{name} && xcodegen generate && cd SampleApp/ && xcodegen generate && cd ../ && pod install && open #{name}.xcworkspace"
    end 

end