
source 'https://cdn.cocoapods.org/'

platform :ios, '11.0'

inhibit_all_warnings!
use_frameworks!

workspace 'FinanceFoundations'

target 'FinanceFoundations' do

  pod 'SwiftLint'
  pod 'SwiftGen', '6.5.1'

  target 'FinanceFoundationsTests' do
      #pod 'Dependency', '~> 1.0.0'
  end
end

target 'SampleApp' do
  project 'SampleApp/SampleApp'
  pod 'FinanceFoundations', :path => './'
end