source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

inhibit_all_warnings!
use_frameworks!

workspace 'Feature1'

target 'Feature1' do
  pod 'SwiftGen', '6.5.1'  
  pod 'Feature1Interface', :path => '../Feature1Interface'

  target 'Feature1Tests' do
      #pod 'Dependency', '~> 1.0.0'
  end
end

target 'SampleApp' do
  project 'SampleApp/SampleApp'
  pod 'Feature1', :path => './'
  pod 'Feature1Assembly', :path => '../Feature1Assembly'

  # DI
  pod 'Swinject', '~> 2.0'
  pod 'SwinjectAutoregistration', '~> 2.0'

end