
source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

inhibit_all_warnings!
use_frameworks!

workspace 'Transfers'

target 'Transfers' do

  pod 'SwiftLint'
  pod 'SwiftGen', '6.5.1'
  pod 'ContactListInterface', :path => '../FinanceUI/ContactListInterface'
  pod 'Confirmation', :path => '../Confirmation'
  pod 'Components', :path => '../Components'

  target 'TransfersTests' do
      #pod 'Dependency', '~> 1.0.0'
  end
end

target 'SampleApp' do
  project 'SampleApp/SampleApp'
  pod 'Transfers', :path => './'
end