source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

inhibit_all_warnings!
use_frameworks!

workspace 'Home'

target 'Home' do
  pod 'SwiftGen', '6.5.1'  
  pod 'HomeInterface', :path => '../HomeInterface'
  
  pod 'Components', :path => '../../Components'
  pod 'UserProfile', :path => '../../UserProfile'
  pod 'ActivityDetails', :path => '../../ActivityDetails'

  target 'HomeTests' do
      #pod 'Dependency', '~> 1.0.0'
  end
end

target 'SampleApp' do
  project 'SampleApp/SampleApp'
  pod 'Home', :path => './'
  pod 'HomeAssembly', :path => '../HomeAssembly'

  # DI
  pod 'Swinject', '~> 2.0'
  pod 'SwinjectAutoregistration', '~> 2.0'

end
