
source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

inhibit_all_warnings!
use_frameworks!

workspace 'Components'

target 'Components' do

  pod 'SwiftLint'
  pod 'SwiftGen', '6.5.1'
  pod 'Swinject', '~> 2.0'
  pod 'FinanceFoundations', :path => '../FinanceFoundations'
  
  target 'ComponentsTests' do
      #pod 'Dependency', '~> 1.0.0'
  end
end

target 'SampleApp' do
  project 'SampleApp/SampleApp'
  pod 'Components', :path => './'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
